export const openApiSpec = {
  openapi: '3.0.3',
  info: {
    title: 'University API',
    description: 'REST API for university management',
    version: '1.0.0',
  },
  tags: [
    { name: 'Students', description: 'Manage university students' },
    { name: 'Courses', description: 'Manage university courses. Requires API Key authentication.' },
    { name: 'Teachers', description: 'Manage university teachers' },
  ],
  paths: {
    '/api/students': {
      get: {
        tags: ['Students'],
        summary: 'Get all students',
        operationId: 'getStudents',
        parameters: [
          { name: 'page', in: 'query', schema: { type: 'integer', default: 1 } },
          { name: 'limit', in: 'query', schema: { type: 'integer', default: 10 } },
          { name: 'sortBy', in: 'query', schema: { type: 'string', enum: ['firstName', 'lastName', 'email', 'year', 'gpa', 'createdAt'] } },
          { name: 'sortOrder', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'] } },
        ],
        responses: { '200': { description: 'Successful response', content: { 'application/json': { schema: { $ref: '#/components/schemas/PaginatedStudents' } } } } },
      },
      post: {
        tags: ['Students'],
        summary: 'Create a student',
        operationId: 'createStudent',
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/StudentInput' } } } },
        responses: { '201': { description: 'Created', content: { 'application/json': { schema: { $ref: '#/components/schemas/StudentResponse' } } } } },
      },
    },
    '/api/students/{id}': {
      get: { tags: ['Students'], summary: 'Get student by ID', operationId: 'getStudentById', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'Found', content: { 'application/json': { schema: { $ref: '#/components/schemas/StudentResponse' } } } }, '404': { description: 'Not found' } } },
      put: { tags: ['Students'], summary: 'Update student', operationId: 'updateStudent', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/StudentInput' } } } }, responses: { '200': { description: 'Updated' }, '404': { description: 'Not found' } } },
      patch: { tags: ['Students'], summary: 'Patch student', operationId: 'patchStudent', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/StudentInput' } } } }, responses: { '200': { description: 'Updated' }, '404': { description: 'Not found' } } },
      delete: { tags: ['Students'], summary: 'Delete student', operationId: 'deleteStudent', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { '204': { description: 'Deleted' }, '404': { description: 'Not found' } } },
    },
    '/api/students/search': {
      get: { tags: ['Students'], summary: 'Search students', operationId: 'searchStudents', parameters: [{ name: 'q', in: 'query', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'Results', content: { 'application/json': { schema: { type: 'object', properties: { success: { type: 'boolean' }, data: { type: 'array', items: { $ref: '#/components/schemas/Student' } }, total: { type: 'integer' } } } } } } } },
    },
    '/api/students/byYear': {
      get: { tags: ['Students'], summary: 'Get students by year', operationId: 'getStudentsByYear', parameters: [{ name: 'year', in: 'query', schema: { type: 'integer', default: 1 } }], responses: { '200': { description: 'Results' } } },
    },
    '/api/students/byStatus': {
      get: { tags: ['Students'], summary: 'Get students by status', operationId: 'getStudentsByStatus', parameters: [{ name: 'status', in: 'query', schema: { type: 'string', enum: ['active', 'inactive', 'graduated', 'suspended'] } }], responses: { '200': { description: 'Results' } } },
    },
    '/api/courses': {
      get: {
        tags: ['Courses'],
        summary: 'Get all courses',
        operationId: 'getCourses',
        security: [{ apiKeyAuth: [] }],
        parameters: [
          { name: 'page', in: 'query', schema: { type: 'integer', default: 1 } },
          { name: 'limit', in: 'query', schema: { type: 'integer', default: 10 } },
          { name: 'sortBy', in: 'query', schema: { type: 'string', enum: ['code', 'title', 'credits', 'semester'] } },
          { name: 'sortOrder', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'] } },
        ],
        responses: {
          '200': { description: 'Successful response', content: { 'application/json': { schema: { $ref: '#/components/schemas/PaginatedCourses' } } } },
          '401': { description: 'Unauthorized - invalid or missing API Key', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
        },
      },
      post: {
        tags: ['Courses'],
        summary: 'Create a course',
        operationId: 'createCourse',
        security: [{ apiKeyAuth: [] }],
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/CourseInput' } } } },
        responses: {
          '201': { description: 'Created', content: { 'application/json': { schema: { $ref: '#/components/schemas/CourseResponse' } } } },
          '401': { description: 'Unauthorized - invalid or missing API Key', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
        },
      },
    },
    '/api/courses/{id}': {
      get: {
        tags: ['Courses'],
        summary: 'Get course by ID',
        operationId: 'getCourseById',
        security: [{ apiKeyAuth: [] }],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          '200': { description: 'Found', content: { 'application/json': { schema: { $ref: '#/components/schemas/CourseResponse' } } } },
          '401': { description: 'Unauthorized', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
          '404': { description: 'Not found' },
        },
      },
      put: {
        tags: ['Courses'],
        summary: 'Update course',
        operationId: 'updateCourse',
        security: [{ apiKeyAuth: [] }],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/CourseInput' } } } },
        responses: {
          '200': { description: 'Updated', content: { 'application/json': { schema: { $ref: '#/components/schemas/CourseResponse' } } } },
          '401': { description: 'Unauthorized', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
          '404': { description: 'Not found' },
        },
      },
      patch: {
        tags: ['Courses'],
        summary: 'Patch course',
        operationId: 'patchCourse',
        security: [{ apiKeyAuth: [] }],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/CourseInput' } } } },
        responses: {
          '200': { description: 'Updated', content: { 'application/json': { schema: { $ref: '#/components/schemas/CourseResponse' } } } },
          '401': { description: 'Unauthorized', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
          '404': { description: 'Not found' },
        },
      },
      delete: {
        tags: ['Courses'],
        summary: 'Delete course',
        operationId: 'deleteCourse',
        security: [{ apiKeyAuth: [] }],
        parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
        responses: {
          '204': { description: 'Deleted' },
          '401': { description: 'Unauthorized', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
          '404': { description: 'Not found' },
        },
      },
    },
    '/api/courses/search': {
      get: {
        tags: ['Courses'],
        summary: 'Search courses',
        operationId: 'searchCourses',
        security: [{ apiKeyAuth: [] }],
        parameters: [{ name: 'q', in: 'query', required: true, schema: { type: 'string' } }],
        responses: {
          '200': { description: 'Results', content: { 'application/json': { schema: { type: 'object', properties: { success: { type: 'boolean' }, data: { type: 'array', items: { $ref: '#/components/schemas/Course' } }, total: { type: 'integer' } } } } } },
          '401': { description: 'Unauthorized', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } },
        },
      },
    },
    '/api/teachers': {
      get: { tags: ['Teachers'], summary: 'Get all teachers', operationId: 'getTeachers', parameters: [{ name: 'page', in: 'query', schema: { type: 'integer', default: 1 } }, { name: 'limit', in: 'query', schema: { type: 'integer', default: 10 } }, { name: 'sortBy', in: 'query', schema: { type: 'string', enum: ['firstName', 'lastName', 'department', 'title'] } }, { name: 'sortOrder', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'] } }], responses: { '200': { description: 'Successful response', content: { 'application/json': { schema: { $ref: '#/components/schemas/PaginatedTeachers' } } } } } },
      post: { tags: ['Teachers'], summary: 'Create a teacher', operationId: 'createTeacher', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/TeacherInput' } } } }, responses: { '201': { description: 'Created', content: { 'application/json': { schema: { $ref: '#/components/schemas/TeacherResponse' } } } } } },
    },
    '/api/teachers/{id}': {
      get: { tags: ['Teachers'], summary: 'Get teacher by ID', operationId: 'getTeacherById', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'Found', content: { 'application/json': { schema: { $ref: '#/components/schemas/TeacherResponse' } } } }, '404': { description: 'Not found' } } },
      put: { tags: ['Teachers'], summary: 'Update teacher', operationId: 'updateTeacher', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/TeacherInput' } } } }, responses: { '200': { description: 'Updated' }, '404': { description: 'Not found' } } },
      patch: { tags: ['Teachers'], summary: 'Patch teacher', operationId: 'patchTeacher', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/TeacherInput' } } } }, responses: { '200': { description: 'Updated' }, '404': { description: 'Not found' } } },
      delete: { tags: ['Teachers'], summary: 'Delete teacher', operationId: 'deleteTeacher', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], responses: { '204': { description: 'Deleted' }, '404': { description: 'Not found' } } },
    },
  },
  components: {
    securitySchemes: {
      apiKeyAuth: {
        type: 'apiKey',
        in: 'header',
        name: 'X-API-Key',
        description: 'API Key required for Courses endpoints. Value: university-api-key-2025',
      },
    },
    schemas: {
      Student: {
        type: 'object',
        properties: {
          id: { type: 'string', example: 'Student-0001' },
          studentNumber: { type: 'string', example: 'STU-2023-0001' },
          firstName: { type: 'string', example: 'John' },
          lastName: { type: 'string', example: 'Doe' },
          email: { type: 'string', example: 'john.doe@university.edu' },
          phone: { type: 'string', example: '(555) 123-4567' },
          birthDate: { type: 'string', example: '2000-01-15' },
          status: { type: 'string', enum: ['active', 'inactive', 'graduated', 'suspended'] },
          year: { type: 'integer', example: 2 },
          gpa: { type: 'number', example: 3.5 },
          courses: { type: 'array', items: { type: 'string' } },
          createdAt: { type: 'string' },
        },
      },
      StudentInput: {
        type: 'object',
        properties: {
          studentNumber: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          phone: { type: 'string' },
          birthDate: { type: 'string' },
          status: { type: 'string', enum: ['active', 'inactive', 'graduated', 'suspended'] },
          year: { type: 'integer' },
          gpa: { type: 'number' },
          courses: { type: 'array', items: { type: 'string' } },
        },
      },
      Course: {
        type: 'object',
        properties: {
          id: { type: 'string', example: 'Course-0001' },
          code: { type: 'string', example: 'CS101' },
          title: { type: 'string', example: 'Introduction to Computer Science' },
          description: { type: 'string' },
          credits: { type: 'integer', example: 3 },
          semester: { type: 'string', example: 'Fall 2025' },
          teacherId: { type: 'string', example: 'Teacher-0001' },
          capacity: { type: 'integer', example: 30 },
          enrolled: { type: 'integer', example: 25 },
          status: { type: 'string', enum: ['active', 'inactive', 'full', 'cancelled'] },
        },
      },
      CourseInput: {
        type: 'object',
        properties: {
          code: { type: 'string' },
          title: { type: 'string' },
          description: { type: 'string' },
          credits: { type: 'integer' },
          semester: { type: 'string' },
          teacherId: { type: 'string' },
          capacity: { type: 'integer' },
          enrolled: { type: 'integer' },
          status: { type: 'string', enum: ['active', 'inactive', 'full', 'cancelled'] },
        },
      },
      Teacher: {
        type: 'object',
        properties: {
          id: { type: 'string', example: 'Teacher-0001' },
          employeeNumber: { type: 'string', example: 'EMP-0001' },
          firstName: { type: 'string', example: 'Jane' },
          lastName: { type: 'string', example: 'Smith' },
          email: { type: 'string', example: 'jane.smith@university.edu' },
          department: { type: 'string', example: 'Computer Science' },
          office: { type: 'string', example: 'Science Hall 301' },
          phone: { type: 'string', example: '(555) 987-6543' },
          title: { type: 'string', example: 'Professor' },
        },
      },
      TeacherInput: {
        type: 'object',
        properties: {
          employeeNumber: { type: 'string' },
          firstName: { type: 'string' },
          lastName: { type: 'string' },
          email: { type: 'string' },
          department: { type: 'string' },
          office: { type: 'string' },
          phone: { type: 'string' },
          title: { type: 'string' },
        },
      },
      StudentResponse: { type: 'object', properties: { success: { type: 'boolean' }, data: { $ref: '#/components/schemas/Student' } } },
      CourseResponse: { type: 'object', properties: { success: { type: 'boolean' }, data: { $ref: '#/components/schemas/Course' } } },
      TeacherResponse: { type: 'object', properties: { success: { type: 'boolean' }, data: { $ref: '#/components/schemas/Teacher' } } },
      PaginatedStudents: { type: 'object', properties: { data: { type: 'array', items: { $ref: '#/components/schemas/Student' } }, pagination: { $ref: '#/components/schemas/Pagination' } } },
      PaginatedCourses: { type: 'object', properties: { data: { type: 'array', items: { $ref: '#/components/schemas/Course' } }, pagination: { $ref: '#/components/schemas/Pagination' } } },
      PaginatedTeachers: { type: 'object', properties: { data: { type: 'array', items: { $ref: '#/components/schemas/Teacher' } }, pagination: { $ref: '#/components/schemas/Pagination' } } },
      Pagination: { type: 'object', properties: { page: { type: 'integer' }, limit: { type: 'integer' }, total: { type: 'integer' }, totalPages: { type: 'integer' } } },
      Error: { type: 'object', properties: { success: { type: 'boolean' }, error: { type: 'object', properties: { code: { type: 'string' }, message: { type: 'string' } } } } },
    },
  },
};
